spring.application.name=Family-Event-Reminder
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:16128/railway
spring.datasource.username = root
spring.datasource.password =DOtVGmEZWcDQdrEdPdOijbDAbRSXKerf
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aru571949@gmail.com
spring.mail.password=oswd shxi ysim bqab
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
spring.task.scheduling.time-zone=Asia/Kolkata
server.port=${PORT:8081}